spring:
  application:
    name: dgs-spring-graphql-example

  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /graphql

dgs.reload: true

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
debug: true