name: "Close stale threads"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  default:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v10.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This pull request has been marked as stale because it has been open 1 year with no activity. Remove stale label or comment or this will be closed in 7 days'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'blocked-external'
        days-before-stale: 365
        days-before-close: 7
        days-before-issue-close: -1
